/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.19
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef __adder_WRAP_H__
#define __adder_WRAP_H__

class __DIRECTOR__;


class __DIRECTOR__splice_callback: public splice_callback, public __DIRECTOR__ {

public:
    __DIRECTOR__splice_callback(PyObject *self, int __disown = 1);
    virtual void run(registers *arg0, splice *arg1);
};


#endif /* ___adder_WRAP_H__ */
